### ISSUE TITLE
Unnamed place issue

### ISSUE THREAD

**Issue by volobot-admin** [humazed/google_map_location_picker#59] opened 2020-04-12 09:29 UTC
I had to use this function to solve the issue.
Library always say "unnamed place" even when api keys are enabled.

import 'package:latlong/latlong.dart';
import 'package:geocoder/geocoder.dart';

static Future<Address> getPredictionFromLatLng(LatLng latLng) async {
    try {
      final coordinates = new Coordinates(latLng.latitude, latLng.longitude);
      List<Address> addresses =
      await Geocoder.local.findAddressesFromCoordinates(coordinates);
      Address first = addresses.first;
      print("${first.featureName} : ${first.addressLine}");
      return first;
    } catch (e) {
      return null;
    }
  }

**Comment by humazed** [comment] 2020-04-12 09:40
duplicate of https://github.com/humazed/google_map_location_picker/issues/16

**Closed by humazed** 2020-04-12 09:40 UTC
