### ISSUE TITLE
unnamed place issue

### ISSUE THREAD

**Issue by kittugithubpandey** [humazed/google_map_location_picker#91] opened 2020-07-24 08:34 UTC
unnamed place and if i am searching any place it is giving no result

**Comment by humazed** [comment] 2020-07-26 21:06
duplicate of #16

**Closed by humazed** 2020-07-26 21:06 UTC

**Comment by shahzaib44** [comment] 2021-04-15 12:22
You should place your api metadeta info in

<application>
   <meta-data android:name="com.google.android.geo.API_KEY" android:value="<put your api KEY here"/>  
<application>

and not in other position like for example under:

<application>
   <activity>
      <meta-data android:name="com.google.android.geo.API_KEY" android:value="<put your api KEY here"/>
   <activity>
<application>

This worked for me

**Comment by shahzaib44** [comment] 2021-04-15 12:27
You should place metadata info in android manifest file like this:

application
   meta-data android:name="com.google.android.geo.API_KEY" android:value="<put your api KEY here"/>  
application

and not in other position like for example under:

application
   activity
      meta-data android:name="com.google.android.geo.API_KEY" android:value="<put your api KEY here"/>
   activity
application

This worked for me
