### ISSUE TITLE
Location Address shows unamed Location

### ISSUE THREAD

**Issue by 0Vipin0** [humazed/google_map_location_picker#36] opened 2020-01-07 12:28 UTC
I have used the example to get the location but I have removed the localization. I am getting the Latitude and the Longitude but In place of the address of location It says unnamed location. Please either fix this or provide some solution.
It also throws range error as:
RangeError (index): Invalid value: Valid value range is empty: 0
I have tried looking at the files inside the google_maps_location_picker but I was unable to find anything. 
Thank you in advance.

**Comment by humazed** [comment] 2020-01-07 13:25
This looks to be duplicate of #16 
Feel free to reopen if you disagree

**Closed by humazed** 2020-01-07 13:25 UTC
