### ISSUE TITLE
API Key not found

### ISSUE THREAD

**Issue by eslamwael74** [humazed/google_map_location_picker#25] opened 2019-12-02 21:55 UTC
always throw this and showing a white screen, searching working fine but map not displayed 
`java.lang.RuntimeException: API key not found.  Check that <meta-data android:name="com.google.android.geo.API_KEY" android:value="your API key"/> is in the <application> element of AndroidManifest.xml`

`I/flutter (15156): package:google_map_location_picker/src/map.dart 284:7 | GeolocationStatus.granted
I/flutter (15156): package:google_map_location_picker/src/map.dart 60:7 | position = Lat: 29.9758073, Long: 31.0952241
I/flutter (15156): package:google_map_location_picker/src/map.dart 284:7 | GeolocationStatus.granted
D/Dialog  (15156): mIsSamsungBasicInteraction = false
D/Dialog  (15156): mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
I/Google Maps Android API(15156): Google Play services package version: 19629028
E/MethodChannel#flutter/platform_views(15156): Failed to handle method call
E/MethodChannel#flutter/platform_views(15156): java.lang.RuntimeException: API key not found.  Check that <meta-data android:name="com.google.android.geo.API_KEY" android:value="your API key"/> is in the <application> element of AndroidManifest.xml
E/MethodChannel#flutter/platform_views(15156): 	at com.google.maps.api.android.lib6.drd.q.b(:com.google.android.gms.dynamite_mapsdynamite@19629065@19.6.29 (100400-0):11)
E/MethodChannel#flutter/platform_views(15156): 	at com.google.maps.api.android.lib6.auth.f.a(:com.google.android.gms.dynamite_mapsdynamite@19629065@19.6.29 (100400-0):16)
E/MethodChannel#flutter/platform_views(15156): 	at com.google.maps.api.android.lib6.impl.g.a(:com.google.android.gms.dynamite_mapsdynamite@19629065@19.6.29 (100400-0):59)
E/MethodChannel#flutter/platform_views(15156): 	at com.google.android.gms.maps.internal.CreatorImpl.a(:com.google.android.gms.dynamite_mapsdynamite@19629065@19.6.29 (100400-0):7)
E/MethodChannel#flutter/platform_views(15156): 	at com.google.android.gms.maps.internal.CreatorImpl.newMapViewDelegate(:com.google.android.gms.dynamite_mapsdynamite@19629065@19.6.29 (100400-0):36)
E/MethodChannel#flutter/platform_views(15156): 	at com.google.android.gms.maps.internal.h.a(:com.google.android.gms.dynamite_mapsdynamite@19629065@19.6.29 (100400-0):43)
E/MethodChannel#flutter/platform_views(15156): 	at cl.onTransact(:com.google.android.gms.dynamite_mapsdynamite@19629065@19.6.29 (100400-0):5)
E/MethodChannel#flutter/platform_views(15156): 	at android.os.Binder.transact(Binder.java:675)
E/MethodChannel#flutter/platform_views(15156): 	at com.google.android.gms.internal.maps.zza.zza(Unknown Source:10)
E/MethodChannel#flutter/platform_views(15156): 	at com.google.android.gms.maps.internal.zzf.zza(Unknown Source:19)
E/MethodChannel#flutter/platform_views(15156): 	at com.google.android.gms.maps.MapView$zzb.createDelegate(Unknown Source:13)
E/MethodChannel#flutter/platform_views(15156): 	at com.google.android.gms.dynamic.DeferredLifecycleHelper.zaa(Unknown Source:18)
E/MethodChannel#flutter/platform_views(15156): 	at com.google.android.gms.dynamic.DeferredLifecycleHelper.onCreate(Unknown Source:22)
E/MethodChannel#flutter/platform_views(15156): 	at com.google.android.gms.maps.MapView.onCreate(Unknown Source:26)
E/MethodChannel#flutter/platform_views(15156): 	at io.flutter.plugins.googlemaps.GoogleMapController.init(GoogleMapController.java:136)
E/MethodChannel#flutter/platform_views(15156): 	at io.flutter.plugins.googlemaps.GoogleMapBuilder.build(GoogleMapBuilder.java:32)
E/MethodChannel#flutter/platform_views(15156): 	at io.flutter.plugins.googlemaps.GoogleMapFactory.create(GoogleMapFactory.java:51)
E/MethodChannel#flutter/platform_views(15156): 	at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:154)
E/MethodChannel#flutter/platform_views(15156): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:550)
E/MethodChannel#flutter/platform_views(15156): 	at android.app.Dialog.show(Dialog.java:391)
E/MethodChannel#flutter/platform_views(15156): 	at android.app.Presentation.show(Presentation.java:267)
E/MethodChannel#flutter/platform_views(15156): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:92)
E/MethodChannel#flutter/platform_views(15156): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:52)
E/MethodChannel#flutter/platform_views(15156): 	at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:97)
E/MethodChannel#flutter/platform_views(15156): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:87)
E/MethodChannel#flutter/platform_views(15156): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:51)
E/MethodChannel#flutter/platform_views(15156): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#flutter/platform_views(15156): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#flutter/platform_views(15156): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
E/MethodChannel#flutter/platform_views(15156): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/platform_views(15156): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#flutter/platform_views(15156): 	at android.os.Looper.loop(Looper.java:181)
E/MethodChannel#flutter/platform_views(15156): 	at android.app.ActivityThread.main(ActivityThread.java:7076)
E/MethodChannel#flutter/platform_views(15156): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(15156): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#flutter/platform_views(15156): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
E/flutter (15156): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, API key not found.  Check that <meta-data android:name="com.google.android.geo.API_KEY" android:value="your API key"/> is in the <application> element of AndroidManifest.xml, null)
E/flutter (15156): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter (15156): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
E/flutter (15156): <asynchronous suspension>
E/flutter (15156): #2      AndroidViewController._create (package:flutter/src/services/platform_views.dart:639:54)
E/flutter (15156): <asynchronous suspension>
E/flutter (15156): #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:556:14)
E/flutter (15156): <asynchronous suspension>
E/flutter (15156): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:189:29)
E/flutter (15156): <asynchronous suspension>
E/flutter (15156): #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:170:5)
E/flutter (15156): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1604:9)
E/flutter (15156): #7      RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
E/flutter (15156): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
E/flutter (15156): #9      RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:392:13)
E/flutter (15156): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
E/flutter (15156): #11     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
E/flutter (15156): #12     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:443:7)
E/flutter (15156): #13     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
E/flutter (15156): #14     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
E/flutter (15156): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
E/flutter (15156): #16     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (15156): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
E/flutter (15156): #18     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (15156): #19     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1214:11)
E/flutter (15156): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
E/flutter (15156): #21     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
E/flutter (15156): #22     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:443:7)
E/flutter (15156): #23     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
E/flutter (15156): #24     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
E/flutter (15156): #25     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1496:7)
E/flutter (15156): #26     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
E/flutter (15156): #27     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
E/flutter (15156): #28     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
E/flutter (15156): #29     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
E/flutter (15156): #30     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
E/flutter (15156): #31     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
E/flutter (15156): #32     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&Schedul
I/flutter (15156): RangeError (index): Invalid value: Valid value range is empty: 0
`

**Comment by humazed** [comment] 2019-12-03 01:06
Duplicate of #18

**Closed by humazed** 2019-12-03 01:06 UTC

**Comment by eslamwael74** [comment] 2019-12-03 07:37
@humazed i think that's different

**Comment by eslamwael74** [comment] 2019-12-03 13:55
I tiered to solving this issue but still same error occurred, i'm init Android integrations only and not working on Android.
Any idea? 
@humazed

**Comment by humazed** [comment] 2019-12-04 10:07
in the android app in `AndroidManifest.xml` replace `your API key` with the actual key.
