### ISSUE TITLE
iOS: fatal error: 'google_map_location_picker/google_map_location_picker-Swift.h' file not found

### ISSUE THREAD

**Issue by TennisAndy** [humazed/google_map_location_picker#19] opened 2019-11-09 07:19 UTC
Hi, I builded for iOS device and I got this error:
`    === BUILD TARGET path_provider OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/wunu/workspace/flutter/.pub-cache/hosted/pub.flutter-io.cn/google_map_location_picker-2.1.0/ios/Classes/GoogleMapLocationPickerPlugin.m:2:9: fatal error: 'google_map_location_picker/google_map_location_picker-Swift.h' file not found
    #import <google_map_location_picker/google_map_location_picker-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.`

version: 
  google_map_location_picker: 2.1.0

It is working fine on Android, please advise, thank you!

**Comment by Saif2nsari** [comment] 2019-11-09 14:15
Did you find a solution ??

**Comment by humazed** [comment] 2019-11-09 15:44
I have updated the library please try again with version 2.1.1
and don't forget to add your key. 
https://github.com/humazed/google_map_location_picker#ios

**Comment by TennisAndy** [comment] 2019-11-11 06:27
> I have updated the library please try again with version 2.1.1
> and don't forget to add your key.
> https://github.com/humazed/google_map_location_picker#ios

Thank you for quick response!
But I update library version to 2.1.1, it says:
`Running "flutter pub get" in flutter_smart_link...              
Because flutter_smart_link depends on google_map_location_picker 2.1.1 which doesn't match any versions, version solving failed.
pub get failed (1)`

**Comment by humazed** [comment] 2019-11-11 15:02
sorry for that there was an error uploading 2.1.1 version it's now fixed.

**Comment by TennisAndy** [comment] 2019-11-12 01:32
@humazed Still the error 2.1.1！

`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15 19A603, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

• No issues found!
`
Here is my env.

**Comment by humazed** [comment] 2019-11-12 20:04
I have tried it and it works for me

can you please double check it on a new project.
```
  google_map_location_picker: ^2.1.1
```

**Comment by JesperBllnbm** [comment] 2019-12-02 09:02
Hi,

I have the same problem in the current version 2.1.2

`Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/dceuh0o/flutter/.pub-cache/hosted/pub.dartlang.org/google_map_location_picker-2.1.2/ios/Classes/GoogleMapLocationPickerPlugin.m:2:9: fatal error: 'google_map_location_picker/google_map_location_picker-Swift.h' file not found
    #import <google_map_location_picker/google_map_location_picker-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build systemnote: Planning buildnote: Constructing build description`

any help is really appreciated :)

**Comment by humazed** [comment] 2019-12-03 01:08
I can reproduce the error and will probably will release a new update today.

**Comment by humazed** [comment] 2019-12-09 07:27
This only happens on Objective-C projects.

the solution is the same as #23 

Update to `google_map_location_picker: ^2.1.2`

you also need to edit your `Podfile`
```
target 'Runner' do
  use_frameworks! # <--- add this
  ...
end
```

See this [issue](https://github.com/flutter/flutter/issues/16049) for more details.

**Closed by humazed** 2019-12-09 07:27 UTC
