### ISSUE TITLE
Unnamed place

### ISSUE THREAD

**Issue by farrelanelca** [humazed/google_map_location_picker#66] opened 2020-05-16 09:49 UTC
every i move the pin or i find from the text field, the widged `locationCard` always showing text unnamed place (from `map.dart`)

![Screenshot_2020-05-16-16-48-42-06_40e95b363286b7d4c62e5d0d38f11a5a](https://user-images.githubusercontent.com/42790915/82116594-2d0d7780-9795-11ea-847f-ddcb0ed0e4e8.jpg)

**Comment by Bestfastfire** [comment] 2020-05-22 06:09
This problem is caused when you use a key what don't have permissions to access this feature

**Comment by humazed** [comment] 2020-05-30 15:46
Duplicate of #16

**Closed by humazed** 2020-05-30 15:46 UTC
